---
apiVersion: daemons.redhat.com/v1alpha1
kind: TangServer
metadata:
  name: tangserver-scaleout
  namespace: nbde
  finalizers:
    - finalizer.daemons.tangserver.redhat.com
spec:
  # Add fields here
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  replicas: 2
