---
apiVersion: nbde.openshift.io/v1alpha1
kind: TangServer
metadata:
  name: tangserver-multi1
  namespace: nbde
  finalizers:
    - finalizer.nbde.tangserver.openshift.io
spec:
  replicas: 2
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  persistentVolumeClaim: "tangserver-pvc-multi1"
  serviceListenPort: 9998
---
apiVersion: nbde.openshift.io/v1alpha1
kind: TangServer
metadata:
  name: tangserver-multi2
  namespace: nbde
  finalizers:
    - finalizer.nbde.tangserver.openshift.io
spec:
  replicas: 3
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  persistentVolumeClaim: "tangserver-pvc-multi2"
  serviceListenPort: 9999
