---
apiVersion: nbde.openshift.io/v1alpha1
kind: TangServer
metadata:
  name: tangserver-functional1
  namespace: nbde
  finalizers:
    - finalizer.nbde.tangserver.openshift.io
spec:
  replicas: 1
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  persistentVolumeClaim: "tangserver-pvc-functional1"
  serviceListenPort: 3333
---
apiVersion: nbde.openshift.io/v1alpha1
kind: TangServer
metadata:
  name: tangserver-functional2
  namespace: nbde
  finalizers:
    - finalizer.nbde.tangserver.openshift.io
spec:
  replicas: 1
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  persistentVolumeClaim: "tangserver-pvc-functional2"
  serviceListenPort: 4444
