---
apiVersion: nbde.openshift.io/v1alpha1
kind: TangServer
metadata:
  name: tangserver-none-cluster-ip
  namespace: nbde
  finalizers:
    - finalizer.nbde.tangserver.openshift.io
spec:
  replicas: 1
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  clusterIP: "None"
  serviceType: "ClusterIP"
