---
name: "Test Execution"

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.wordlist.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.wordlist.txt'
  workflow_dispatch:

jobs:
  test-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - fedora:latest
    container:
      image: ${{matrix.os}}
      env:
        DISTRO: ${{matrix.os}}
        run:
          set -eu
          echo "DISTRO:${DISTRO}"
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install dependencies (kubectl, helm, clamscan, make)
      run: |
        sh .github/workflows/scripts/install_dependencies.sh

    - name: Run test
      run: |
        pushd .github/workflows/scripts/; ./tang_operator_test.sh; popd
